window.SCENES = {
  1: {
    label: "official source",
    accent: "#7ad4df",
    kicker: "openai engineering",
    headline: ["别只看", "一百万行代码"],
    note: "真正的变化：软件工程被改造成 Codex 能执行、能检查的环境。",
    title: "SOURCE DOSSIER",
    render: "source"
  },
  2: {
    label: "source numbers",
    accent: "#8eb2e0",
    kicker: "original numbers",
    headline: ["先看", "原始数字"],
    note: "这些数字来自 OpenAI 原文，不是二次转述。",
    title: "SOURCE METRICS",
    render: "metrics"
  },
  3: {
    label: "role inversion",
    accent: "#7ad4df",
    kicker: "human attention",
    headline: ["人类掌舵", "Codex 执行"],
    note: "核心不是代码更多，而是人的工作重心被上移。",
    title: "ROLE INVERSION",
    render: "role"
  },
  4: {
    label: "agent-shaped repo",
    accent: "#dfb65f",
    kicker: "empty repository",
    headline: ["仓库先被", "Agent 塑形"],
    note: "不是先写完系统，再让 AI 适配。",
    title: "FIRST COMMIT: LATE AUGUST 2025",
    render: "scaffold"
  },
  5: {
    label: "application legibility",
    accent: "#7ad4df",
    kicker: "chrome devtools mcp",
    headline: ["让应用本身", "对 Codex 可见"],
    note: "页面、DOM、导航和修复验证，都进入工具链。",
    title: "APP AS WORKBENCH",
    render: "devtools"
  },
  6: {
    label: "observability",
    accent: "#9fb77d",
    kicker: "logs metrics traces",
    headline: ["运行信号", "变成 Agent 工具"],
    note: "日志、指标、链路追踪，不只是给人看的仪表盘。",
    title: "TEMP LOCAL OBSERVABILITY STACK",
    render: "observability"
  },
  7: {
    label: "repository knowledge",
    accent: "#dfb65f",
    kicker: "map not manual",
    headline: ["AGENTS.md 是地图", "docs/ 是系统记录"],
    note: "约一百行地图，指向版本化、可维护的知识库。",
    title: "KNOWLEDGE LAYOUT",
    render: "knowledge"
  },
  8: {
    label: "agent legibility",
    accent: "#e56357",
    kicker: "what cannot be seen",
    headline: ["看不见的知识", "几乎等于不存在"],
    note: "隐性知识必须进入仓库，才会稳定进入 Agent 上下文。",
    title: "VISIBLE KNOWLEDGE BOUNDARY",
    render: "invisible"
  },
  9: {
    label: "architecture invariants",
    accent: "#7ad4df",
    kicker: "enforce taste mechanically",
    headline: ["工程品味", "要被机械化"],
    note: "好的架构不能只靠口头提醒，要变成 lint、边界和错误信息。",
    title: "ARCHITECTURE INVARIANTS",
    render: "architecture"
  },
  10: {
    label: "merge philosophy",
    accent: "#8eb2e0",
    kicker: "throughput changes process",
    headline: ["修正成本变低", "等待成本变高"],
    note: "高吞吐会改变合并策略，但低吞吐团队不能照搬。",
    title: "MERGE STRATEGY SHIFT",
    render: "merge"
  },
  11: {
    label: "agent-generated scope",
    accent: "#9fb77d",
    kicker: "everything in the repo",
    headline: ["Agent-generated", "不只是业务代码"],
    note: "测试、工具、CI、文档、评审，也会成为生成对象。",
    title: "GENERATION SURFACE AREA",
    render: "scope"
  },
  12: {
    label: "autonomy loop",
    accent: "#7ad4df",
    kicker: "one prompt to merged change",
    headline: ["自治不是魔法", "是闭环"],
    note: "工具、验证、反馈和升级路径，共同组成端到端工作流。",
    title: "END-TO-END AUTONOMY LOOP",
    render: "loop"
  },
  13: {
    label: "entropy control",
    accent: "#dfb65f",
    kicker: "garbage collection",
    headline: ["熵也要", "被治理"],
    note: "Agent 会放大模式，好坏都会放大。",
    title: "ENTROPY MANAGEMENT",
    render: "entropy"
  },
  14: {
    label: "final compression",
    accent: "#7ad4df",
    kicker: "the real lesson",
    headline: ["模型负责生成", "Harness 负责治理"],
    note: "企业真正需要的不是更炫的 demo，而是 AI 基础设施。",
    title: "FINAL MODEL",
    render: "final"
  }
};

window.BEAT_DESIGN = {
  1: { focus: ["headline"], progress: 0.02 },
  2: { focus: ["source-card"], progress: 0.04 },
  3: { focus: ["visible", "control", "verify"], progress: 0.05 },
  4: { focus: ["metric-users"], progress: 0.07 },
  5: { focus: ["metric-zero"], progress: 0.08 },
  6: { focus: ["metric-months", "metric-lines", "metric-prs"], progress: 0.10 },
  7: { focus: ["metric-time"], progress: 0.12 },
  8: { focus: ["metric-rate"], progress: 0.13 },
  9: { focus: ["metric-engineers", "metric-users"], progress: 0.15 },
  10: { focus: ["headline"], progress: 0.17 },
  11: { focus: ["human", "agent"], progress: 0.19 },
  12: { focus: ["headline"], progress: 0.21 },
  13: { focus: ["scaffold"], progress: 0.22 },
  14: { focus: ["repo", "ci"], progress: 0.24 },
  15: { focus: ["agents"], progress: 0.25 },
  16: { focus: ["headline"], progress: 0.27 },
  17: { focus: ["app"], progress: 0.29 },
  18: { focus: ["devtools"], progress: 0.31 },
  19: { focus: ["validate"], progress: 0.32 },
  20: { focus: ["app", "devtools", "validate"], progress: 0.34 },
  21: { focus: ["headline"], progress: 0.36 },
  22: { focus: ["worktree"], progress: 0.37 },
  23: { focus: ["vector", "logs", "metrics", "traces"], progress: 0.39 },
  24: { focus: ["codex"], progress: 0.41 },
  25: { focus: ["target"], progress: 0.42 },
  26: { focus: ["codex"], progress: 0.44 },
  27: { focus: ["headline"], progress: 0.46 },
  28: { focus: ["agents-map"], progress: 0.47 },
  29: { focus: ["agents-map"], progress: 0.49 },
  30: { focus: ["docs"], progress: 0.51 },
  31: { focus: ["freshness"], progress: 0.52 },
  32: { focus: ["headline"], progress: 0.54 },
  33: { focus: ["outside-doc", "chat", "tribal", "decision"], progress: 0.56 },
  34: { focus: ["headline"], progress: 0.58 },
  35: { focus: ["ladder"], progress: 0.59 },
  36: { focus: ["providers"], progress: 0.61 },
  37: { focus: ["ladder", "providers"], progress: 0.63 },
  38: { focus: ["lint"], progress: 0.64 },
  39: { focus: ["headline"], progress: 0.66 },
  40: { focus: ["headline"], progress: 0.68 },
  41: { focus: ["pr-pills"], progress: 0.69 },
  42: { focus: ["merge-model"], progress: 0.71 },
  43: { focus: ["headline"], progress: 0.73 },
  44: { focus: ["scope-grid"], progress: 0.75 },
  45: { focus: ["headline"], progress: 0.76 },
  46: { focus: ["check", "bug"], progress: 0.78 },
  47: { focus: ["patch", "test", "pr"], progress: 0.80 },
  48: { focus: ["feedback", "escalate", "merge"], progress: 0.81 },
  49: { focus: ["loop-all"], progress: 0.83 },
  50: { focus: ["headline"], progress: 0.85 },
  51: { focus: ["old"], progress: 0.86 },
  52: { focus: ["principles"], progress: 0.88 },
  53: { focus: ["new", "principles"], progress: 0.90 },
  54: { focus: ["new"], progress: 0.92 },
  55: { focus: ["headline"], progress: 0.93 },
  56: { focus: ["model", "harness"], progress: 0.95 },
  57: { focus: ["governance"], progress: 0.97 },
  58: { focus: ["caveat"], progress: 0.98 },
  59: { focus: ["final-all"], progress: 1.0 }
};
